---

repos:
  - repo: https://github.com/willthames/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        types: [yaml]
        exclude: >
          (?x)^(
            \.travis\.yml|
            molecule/.*/\.molecule/.*|
            molecule/.*/create\.yml
          )$
      - id: ansible-lint
        files: \.travis\.yml
        args: [-x, ANSIBLE0008]
      - id: ansible-lint
        files: molecule/.*/create\.yml
        args: [-x, ANSIBLE0016]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: flake8
      - id: trailing-whitespace
