---

group: stable
dist: bionic

os:
  - linux

language: python
python:
  - 3.6
cache: pip

branches:
  only:
    - develop
    - master

env:
  - ANSIBLE_INSTALL_VERSION=2.8.18
  - ANSIBLE_INSTALL_VERSION=2.9.16

services:
  - docker

install:
  - make deps

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
