---

- name: Converge
  hosts: all

  roles:
    - role: sansible.users_and_groups
      sansible_users_and_groups_users:
        - name: php

    - role: sansible.nginx

    - role: php
      sansible_php_fpm_chroot: /home/php/molecule/
      sansible_php_fpm_description: Molecule Test
      sansible_php_fpm_group: php
      sansible_php_fpm_user: php
      sansible_php_version: php7.0
