---

- name: Prepare
  hosts: all
  gather_facts: no

  tasks:
    - name: Install Python for Ansible
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-zipstream)
      changed_when: no

    - name: Install apt-transport-https, lsb-release, net-tools
      become: yes
      apt:
        name:
          - apt-transport-https
          - gpg
          - lsb-release
          - net-tools
          - python3-setuptools
          - unzip
        update_cache: yes

    - name: Symlink pip3 for TestInfra
      become: yes
      file:
        dest: /usr/bin/pip
        force: yes
        mode: 0751
        src: /usr/bin/pip3
        state: link
